"""Importing this package registers the generation tools."""
from . import setup  # noqa: F401
from . import image  # noqa: F401
from . import video  # noqa: F401
from . import audio  # noqa: F401
from . import extract  # noqa: F401
from . import analyze  # noqa: F401
from . import stitch  # noqa: F401
from . import jobs  # noqa: F401
